from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

class Questions(db.Model):
    question_id = db.Column(db.Integer, primary_key=True, unique=True, autoincrement=True)
    content_japanese = db.Column(db.String)
    content_english = db.Column(db.String)
    content_german = db.Column(db.String)
    content_french = db.Column(db.String)
    content_spanish = db.Column(db.String)
    content_italian = db.Column(db.String)
    content_dutch = db.Column(db.String)
    content_portuguese = db.Column(db.String)
    content_french_canada = db.Column(db.String)
    content_catalan = db.Column(db.String)
    content_russian = db.Column(db.String)
    choice1_japanese = db.Column(db.String)
    choice1_english = db.Column(db.String)
    choice1_german = db.Column(db.String)
    choice1_french = db.Column(db.String)
    choice1_spanish = db.Column(db.String)
    choice1_italian = db.Column(db.String)
    choice1_dutch = db.Column(db.String)
    choice1_portuguese = db.Column(db.String)
    choice1_french_canada = db.Column(db.String)
    choice1_catalan = db.Column(db.String)
    choice1_russian = db.Column(db.String)
    choice2_japanese = db.Column(db.String)
    choice2_english = db.Column(db.String)
    choice2_german = db.Column(db.String)
    choice2_french = db.Column(db.String)
    choice2_spanish = db.Column(db.String)
    choice2_italian = db.Column(db.String)
    choice2_dutch = db.Column(db.String)
    choice2_portuguese = db.Column(db.String)
    choice2_french_canada = db.Column(db.String)
    choice2_catalan = db.Column(db.String)
    choice2_russian = db.Column(db.String)
    worldwide = db.Column(db.Boolean)
    start_date = db.Column(db.BigInteger)
    end_date = db.Column(db.BigInteger)

